server:
  port: 10080
spring:
  application:
    name: base_util
#  cloud:
#    nacos:
#      #        服务发现
#      discovery:
#        server-addr: localhost:8848



  data:
    redis:
      host: localhost
      port: 6379
      password: 'starlive123'
      timeout: 60000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms